# name = 'Theme name'
# license = 'MIT'
# licenselink = 'https://github.com/owner/repo/LICENSE'
# description = 'Theme description'
#
# # The home page of the theme, where the source can be found
# homepage = 'https://github.com/owner/repo'
#
# # If you have a running demo of the theme
# demosite = 'https://owner.github.io/repo'
#
# # Taxonomy terms
# tags = ['blog', 'company']
# features = ['some', 'awesome', 'features']
#
# # If the theme has multiple authors
# authors = [
#   { name = 'Name of author', homepage = 'Website of author' },
#   { name = 'Name of author', homepage = 'Website of author' },
# ]
#
# # If the theme has a single author
# [author]
# name = 'Your name'
# homepage = 'Your website'
#
# # If porting an existing theme
# [original]
# author = 'Name of original author'
# homepage = 'Website of original author'
# repo = 'https://github.com/owner/repo'


name = "The Monospace Web"
license = "MIT"
licenselink = "https://github.com/donaldgifford/the-monospace-web/blob/main/LICENSE"
description = "Monospace web for Hugo"
homepage = "https://github.com/donaldgifford/the-monospace-web/"
# homepage = "https://github.com/donaldgifford/hugo-theme-the-monospace-web/"
demosite = ""
tags = [
  "blog",
  "gallery",
  "portfolio",
  "console",
  "terminal",
  "clean",
  "personal",
  "minimal",
  "monotone",
  "simple",
  "technical",
  "responsive",
  "mobile",
  "minimalist",
  "retro",
  "animation",
]
features = ["disqus", "responsive", "google analytics"]
min_version = "0.01"

[author]
name = "Donald Gifford"
homepage = "https://donald.dev"
github = "https://github.com/donaldgifford"
